services:
  database:
    build: ./database
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database-network

  backend:
    build: ./simple-api
    networks:
      - database-network
      - frontend-network
    depends_on:
      - database

  httpd:
    build: ./http-server
    ports:
      - "80:80"
    networks:
      - frontend-network
    depends_on:
      - backend

networks:
  database-network:
  frontend-network:

volumes:
  db-data: